name: test

on:
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Set up uv
              uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0

            - name: Install dependencies
              run: uv sync --locked

            - name: Ruff check
              run: uv run ruff check --output-format github

            - name: Ruff format
              run: uv run ruff format --check --diff

    unittest:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.9', '3.14']
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Set up uv
              uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: uv sync --locked

            - name: Run pytest
              run: uv run pytest -v --cov --cov-report xml --cov-report term

            - name: Upload coverage reports to Codecov
              if: matrix.python-version == '3.9'
              uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: MIERUNE/gtfs-parser
