name: test

on:
  pull_request:
    branches: [ main ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install
      
      - name: unittest
        run: poetry run python -m unittest discover .