name: test

on:
    pull_request:
        branches: [main]

jobs:
    unittest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                  python -m pip install poetry
                  poetry install

            - name: Run pytest
              run: poetry run pytest -v --cov --cov-report xml --cov-report term

            - name: Upload coverage
              uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: ./coverage.xml
                  flags: unittests
                  env_vars: OS,PYTHON
                  fail_ci_if_error: true
