name: test

on:
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up uv
              uses: astral-sh/setup-uv@v7

            - name: Install dependencies
              run: uv sync --locked

            - name: Ruff check
              run: uv run ruff check --output-format github

            - name: Ruff format
              run: uv run ruff format --check --diff

    unittest:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.9', '3.14']
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up uv
              uses: astral-sh/setup-uv@v7
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: uv sync --locked

            - name: Run pytest
              run: uv run pytest -v --cov --cov-report xml --cov-report term

            - name: Upload coverage reports to Codecov
              if: matrix.python-version == '3.9'
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: MIERUNE/gtfs-parser
